<script setup lang="ts">
// A quiet, full-screen reader for the open note. It sets the writing in clean typography — the same
// content, without the paper, the ink, or any chrome — so a long note can be read or reviewed
// without the tools in the way. The reading size can be nudged for comfort, and Escape closes it.
import { computed, ref } from 'vue'
import { useDocument } from '@/store/document'
import { noteBodyHtml } from '@/export/toText'
import Icon from './Icon.vue'
import { useFocusTrap } from './useFocusTrap'

const emit = defineEmits<{ (e: 'close'): void }>()
const documentStore = useDocument()

const root = ref<HTMLElement | null>(null)
useFocusTrap(root, () => emit('close'))

// The note rendered to clean HTML. It is built by the app from the structured note (text is
// escaped as it is converted), never from anything a reader typed as markup, so it is safe to set.
const html = computed(() => noteBodyHtml(documentStore.doc))

// A comfortable reading size the reader can step up or down; it rides the whole column.
const STEPS = [16, 18, 20, 23, 26]
const sizeStep = ref(1)
const fontSize = computed(() => STEPS[sizeStep.value])
function larger() {
  if (sizeStep.value < STEPS.length - 1) sizeStep.value += 1
}
function smaller() {
  if (sizeStep.value > 0) sizeStep.value -= 1
}
</script>

<template>
  <div ref="root" class="reader" role="dialog" aria-modal="true" aria-label="Reading" tabindex="-1">
    <header class="bar">
      <span class="label">Reading</span>
      <div class="controls">
        <button class="ctl" title="Smaller text" :disabled="sizeStep === 0" @click="smaller">
          <Icon name="paragraph" :size="13" />−
        </button>
        <button class="ctl" title="Larger text" :disabled="sizeStep === STEPS.length - 1" @click="larger">
          <Icon name="paragraph" :size="17" />+
        </button>
        <button class="close" title="Close reading (Esc)" @click="emit('close')">
          <Icon name="close" :size="18" />
        </button>
      </div>
    </header>
    <!-- eslint-disable-next-line vue/no-v-html -- html is generated by the app from the structured note with all text escaped, never raw user markup -->
    <article class="page" :style="{ fontSize: `${fontSize}px` }" v-html="html" />
  </div>
</template>

<style scoped>
.reader {
  position: fixed;
  inset: 0;
  z-index: 95;
  background: var(--surface, #fff);
  color: var(--text, #23232e);
  display: flex;
  flex-direction: column;
  overflow: hidden;
}
.bar {
  display: flex;
  align-items: center;
  justify-content: space-between;
  padding: 12px 18px;
  border-bottom: 1px solid var(--border);
  flex-shrink: 0;
}
.label {
  font-size: 12px;
  text-transform: uppercase;
  letter-spacing: 0.06em;
  color: var(--text-muted);
}
.controls {
  display: flex;
  align-items: center;
  gap: 6px;
}
.ctl,
.close {
  display: inline-flex;
  align-items: center;
  gap: 1px;
  border: none;
  background: transparent;
  color: var(--text-muted);
  border-radius: 9px;
  padding: 7px 9px;
  font: inherit;
  font-size: 13px;
  cursor: pointer;
}
.ctl:hover:not(:disabled),
.close:hover {
  background: var(--surface-sunken);
  color: var(--text);
}
.ctl:disabled {
  opacity: 0.4;
  cursor: default;
}
.page {
  margin: 0 auto;
  padding: 40px 24px 22vh;
  max-width: 42rem;
  width: 100%;
  overflow-y: auto;
  line-height: 1.7;
}

/* Clean typography for the rendered note. These target the generated HTML, so they are not scoped
   to component elements; kept deliberate and quiet so the writing is the focus. */
.page :deep(h1) {
  font-size: 1.7em;
  font-weight: 700;
  margin: 0 0 0.6em;
  color: var(--brand, var(--accent));
}
.page :deep(h2) {
  font-size: 1.3em;
  font-weight: 700;
  margin: 1.4em 0 0.4em;
}
.page :deep(h3) {
  font-size: 1.1em;
  font-weight: 700;
  margin: 1.2em 0 0.3em;
}
.page :deep(p) {
  margin: 0 0 0.9em;
}
.page :deep(ul),
.page :deep(ol) {
  margin: 0 0 0.9em;
  padding-left: 1.4em;
}
.page :deep(li) {
  margin: 0.2em 0;
}
.page :deep(blockquote) {
  border-left: 3px solid var(--border);
  margin: 1em 0;
  padding-left: 1em;
  color: var(--text-muted);
}
.page :deep(pre),
.page :deep(code) {
  font-family: ui-monospace, SFMono-Regular, Menlo, monospace;
  font-size: 0.9em;
}
.page :deep(pre) {
  background: var(--surface-sunken);
  padding: 12px 14px;
  border-radius: 10px;
  overflow-x: auto;
}
.page :deep(table) {
  border-collapse: collapse;
  margin: 1em 0;
  width: 100%;
}
.page :deep(td),
.page :deep(th) {
  border: 1px solid var(--border);
  padding: 6px 10px;
  text-align: left;
}
.page :deep(hr) {
  border: none;
  border-top: 1px solid var(--border);
  margin: 1.6em 0;
}
.page :deep(img) {
  max-width: 100%;
  border-radius: 8px;
}
</style>
